name: Cargo Check

on:
  push:

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Cargo Check
      run: cargo check